# Generated by Django 3.0.5 on 2020-10-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='FIRST', max_length=255),
        ),
    ]
