# Generated by Django 3.0.5 on 2020-10-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0006_auto_20201027_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Acerca de ....', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='Crea una categoria', max_length=255),
        ),
    ]
